version: '3'
services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Docker2021"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
  book-app:
    build: .
    environment:
      DatabaseServer: "mssql-server"
      DatabasePort: "1433"
      DatabaseUser: "SA"
      DatabasePassword: "Docker2021"
      DatabaseName: "booksdb"
    ports:
      - "5000:80"
        